### ISSUE TITLE
Which game version do I need?

### ISSUE THREAD

**Issue by Alpha-Radke** [mRally2/ExtraUIOptions#1]
For some reason your mods don't work on my game. I open the executables and they run for a second then close wheather the game is running or not so pressing a key to enable a mod doesn't do anything. I started the game with The Run v1.1 Unlocker but idk if that even made any changes

**Comment by mRally2** [comment]
All trainers should work fine for either executable version (unlocker or vanilla). I have sent these trainers to multiple people before release and worked fine. Not sure what the problem is. Turn off antivirus and redownload the trainer. Maybe your antivirus deleted the stuff inside the exe when it got detected. It’s a false positive as far as I know. It gets detected because it has stuff inside to make changes to memory.

**Comment by Alpha-Radke** [comment]
I have zero antiviruses even defender is completely removed. I think my Windows 10 version (1803) doesn't have the required software tools to run the executables so maybe double check those? which depends on how you built the executables

Are Intel UHD GPUs supported cuz I use them and they don't support Vulkan API at all

**Comment by mRally2** [comment]
Executables were built using Cheat Engine’s trainer maker. If antivirus is not a problem then I have no clue, sorry. My intention with all of these trainer prototypes is to get people into modding/researching about the game to hopefully get more stuff discovered, get new stuff like frosty support, build a server emulator... If there were people willing to port all of these to a .dll or .asi I would upload the raw cheat table aswell.

**Comment by Alpha-Radke** [comment]
Thanks for your attention I will keep an eye on and test the game on different systems

**Comment by mRally2** [comment]
> Thanks for your attention I will keep an eye on and test the game on different systems

I have decided to release the source code of all my trainer prototypes. You have the Cheat Engine cheat table available inside the Code folder. I hope it works fine this way. Cheers.
